graph_file_path: "/opt/movidius/ncappzoo/caffe/AlexNet/graph"
category_file_path: "/opt/movidius/ncappzoo/data/ilsvrc12/imagenet.txt"
network_dimension: 227
channel1_mean: 104.0069879317889
channel2_mean: 116.66876761696767
channel3_mean: 122.6789143406786
scale: 1.0
